name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next
        
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json') }}-
          
    - name: Install dependencies
      run: npm install
      
    - name: Build with Next.js
      run: npm run build
      
    - name: Debug: Check what was built
      run: |
        echo "=== Root directory ==="
        ls -la
        echo "=== .next directory ==="
        find .next -name "*.html" -type f | head -10
        echo "=== Looking for exported static files ==="
        find . -maxdepth 3 -name "index.html" -type f 2>/dev/null
        
    - name: Create proper static export
      run: |
        # Create out directory and copy static files
        mkdir -p out
        # Copy static assets
        cp -r public/* out/ 2>/dev/null || true
        # Copy built HTML files from server directory
        find .next -name "*.html" -exec cp {} out/ \; 2>/dev/null || true
        # Copy static assets from .next
        cp -r .next/static out/_next/static 2>/dev/null || true
        # List what we created
        echo "=== Created out directory ==="
        ls -la out/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4